# Generated by Django 3.0.6 on 2022-10-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0003_product_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['index']},
        ),
    ]
