# Generated by Django 3.0.6 on 2020-08-04 02:28

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=project.models.path_file_name)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
