# Generated by Django 3.0.6 on 2022-10-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on']},
        ),
    ]
